sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (61)") (Background on this error at
: http://sqlalche.me/e/e3q8)

Fix: Make sure the correct port is given

sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'cherry'@'localhost' (using password: YES)") (Background
on this error at: http://sqlalche.me/e/e3q8)

Fix: Use the right user
